upgraded keycloak to 24.0.1
generiekzaakafhandelcomponent/gzac-docker-compose pull request #5
Opened 2024-03-29 15:05 UTC by theo-ritense

2024-03-29 15:13 UTC, Klaas-Ritense commented on docker-compose.yaml
> +      image: openzaak/open-zaak:1.8.2
Please revert

2024-04-02 13:48 UTC, Klaas-Ritense requested changes
Don't downgrade openzaak pls

2024-04-04 06:50 UTC, theo-ritense commented on docker-compose.yaml
> +      image: openzaak/open-zaak:1.8.2
Unintended change. I reverted it.

2024-04-04 07:01 UTC, Klaas-Ritense approved these changes

2024-04-04 11:07 UTC, merged